name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"  # triggers every 12 hours

  workflow_dispatch:  # allows manual trigger from GitHub Actions tab

  push:
    branches:
      - main  # triggers on push to the main branch

jobs:
  generate:
    permissions:
      contents: write  # grants permission to write to the repository
    runs-on: ubuntu-latest
    timeout-minutes: 5  # limits job execution time

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # check out the repository code

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3  # generate the snake animation SVG
        with:
          github_user_name: heybikramjeetsingh  # your GitHub username
          outputs: dist/snake.svg?palette=github-dark  # SVG path with dark theme

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0  # push generated file to the output branch
        with:
          target_branch: output  # branch where snake.svg will be pushed
          build_dir: dist  # directory containing the snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
